config:
  endPoint_real: https://develop.discovery.onsdigital.co.uk/dd/api/versions
  endPoint_stub: http://localhost:20099/datasets
  metadata_editor: https://metadata.publishing.develop.discovery.onsdigital.co.uk
  fileUploader: https://upload.publishing.develop.discovery.onsdigital.co.uk
  jobcreator: https://develop.discovery.onsdigital.co.uk/dd/api/jobs
  backend: real
  file_path: Open-Data-v3_E2E_Tests.csv
#  file_path: AF001EW_v3_E2E_Tests.csv



