config:
#  splitter: http://localhost:21000/splitter
  dbloader: http://localhost:20097
  postgres: jdbc:postgresql://localhost:5432/data_discovery
  endPoint_real:  https://develop.discovery.onsdigital.co.uk/dd/api/versions
  endPoint_stub: http://localhost:20099/datasets
  metadata_editor: http://localhost:23000
  fileUploader: https://upload.publishing.develop.discovery.onsdigital.co.uk
  jobcreator: https://develop.discovery.onsdigital.co.uk/dd/api/jobs
  backend: real
#   or real
#  fileUpload: http://localhost:20019
#  file_path: Open-Data-v3_E2E_Tests.csv
  file_path: AF001EW_v3_E2E_Tests.csv
#  file_path: Open-Data-small.csv
#  file_path: small-example.csv
#  file_path: AF001EW.ArmedForces_in_Databaker_format.csv
#  file_path: WDAT0801new.csv


