config:
  splitter: http://localhost:21000/splitter
  dbloader: http://localhost:9000
  postgres: jdbc:postgresql://localhost:5432/data_discovery
  endPoint_real: http://localhost:8080/datasets
  endPoint_stub: http://localhost:20099/datasets
  backend: real
#   or real
  fileUpload: http://localhost:20019
  file_path: Open-Data-small.csv
#  file_path: small-example.csv
#  file_path: AF001EW.ArmedForces_in_Databaker_format.csv
#  file_path: WDAT0801new.csv


