config:
#  splitter: http://localhost:21000/splitter
  dbloader: http://localhost:20097
  postgres: jdbc:postgresql://localhost:5432/data_discovery
  endPoint_real: https://discovery.onsdigital.co.uk/dd/api/datasets
  endPoint_stub: http://localhost:20098/datasets
  fileUploader: http://localhost:20019
  jobcreator: https://discovery.onsdigital.co.uk/dd/api/jobs
  endPoint_discovery: https://discovery.onsdigital.co.uk/dd/api/datasets
  backend: real
#   or real
  fileUpload: http://localhost:20019
#  file_path: Open-Data-new-format.csv
  file_path: AF001EW-sample.csv
#  file_path: Open-Data-small.csv
#  file_path: small-example.csv
#  file_path: AF001EW.ArmedForces_in_Databaker_format.csv
#  file_path: WDAT0801new.csv


